os:
  - osx
language: cpp
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: icestorm.tar.bz2
    skip_cleanup: true
    on:
      repo: sandeepmistry/icestorm
      branches:
        only:
          - master
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update &&
      brew install libftdi0;
    fi
script:
  - make
  - PREFIX=$PWD/root make install
  - ls -l $PWD/root
  - ls -l $PWD/root/bin
  - otool -L $PWD/root/bin/*
  - cp /usr/local/opt/libftdi0/lib/libftdi.1.dylib $PWD/root/bin/.
  - cp /usr/local/opt/libusb-compat/lib/libusb-0.1.4.dylib $PWD/root/bin/.
  - cp /usr/local/opt/libusb/lib/libusb-1.0.0.dylib $PWD/root/bin/.
  - tar -cvjSf icestorm.tar.bz2 root
  - ls -l icestorm.tar.bz2
