os:
  - osx
language: cpp
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update &&
      brew install libftdi0;
    fi
script:
  - STATIC=1 PREFIX=$PWD/root make
  - STATIC=1 PREFIX=$PWD/root make install
  - ls -l $PWD/root
