os:
  - osx
language: cpp
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update &&
      brew install libftdi0;
    fi
script:
  - PREFIX=$PWD/root make
  - PREFIX=$PWD/root make install
  - ls -l $PWD/root
  - otool -L $PWD/root/bin/*

