os:
  - osx
language: cpp
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: icestorm.tar.bz2
    skip_cleanup: true
    on:
      branch: travis-ci
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update &&
      brew install libftdi0;
    fi
script:
  - make
  - PREFIX=$PWD/root make install
  - ls -l $PWD/root
  - ls -l $PWD/root/bin
  - otool -L $PWD/root/bin/*
  - cp /usr/local/opt/libftdi0/lib/libftdi.1.dylib $PWD/root/bin/.
  - cp /usr/local/opt/libusb-compat/lib/libusb-0.1.4.dylib $PWD/root/bin/.
  - cp /usr/local/opt/libusb/lib/libusb-1.0.0.dylib $PWD/root/bin/.
  - chmod +w $PWD/root/bin/*.dylib
  - install_name_tool -id libftdi.1.dylib $PWD/root/bin/libftdi.1.dylib
  - install_name_tool -id libusb-0.1.4.dylib $PWD/root/bin/libusb-0.1.4.dylib
  - install_name_tool -id libusb-1.0.0.dylib $PWD/root/bin/libusb-1.0.0.dylib
  - install_name_tool -change /usr/local/opt/libusb/lib/libusb-1.0.0.dylib "@executable_path/libusb-1.0.0.dylib" $PWD/root/bin/libusb-0.1.4.dylib
  - install_name_tool -change /usr/local/opt/libusb-compat/lib/libusb-0.1.4.dylib "@executable_path/libusb-0.1.4.dylib" $PWD/root/bin/libftdi.1.dylib
  - chmod -w $PWD/root/bin/*.dylib
  - install_name_tool -change /usr/local/opt/libftdi0/lib/libftdi.1.dylib "@executable_path/libftdi.1.dylib" root/bin/iceprog
  - install_name_tool -change /usr/local/opt/libusb-compat/lib/libusb-0.1.4.dylib "@executable_path/libusb-0.1.4.dylib" root/bin/iceprog
  - tar -cvjSf icestorm.tar.bz2 root
  - ls -l icestorm.tar.bz2
